### ISSUE TITLE
[1.19.2] No Such Method Error

### ISSUE THREAD

**Issue by Reshy** [minecraftabnormals/Neapolitan#174] opened 2023-10-07 03:49 UTC
Crash:  https://pastebin.com/T99Cmwge
Log:  https://pastebin.com/TXdJW800

	Caused by: java.lang.NoSuchMethodError: 'void com.teamabnormals.neapolitan.common.item.MilkshakeItem.<init>(net.minecraft.world.effect.MobEffectCategory, net.minecraft.world.item.Item$Properties)'
		at dev.xkmc.twilightdelight.compat.neapolitan.TDMilkshakeItem.<init>(TDMilkshakeItem.java:17) ~[twilightdelight-1.3.1.jar%23810!/:1.3.1]
		at dev.xkmc.twilightdelight.init.registrate.neapolitan.NeapolitanFoodType.lambda$static$0(NeapolitanFoodType.java:16) ~[twilightdelight-1.3.1.jar%23810!/:1.3.1]
		at dev.xkmc.twilightdelight.init.registrate.neapolitan.NeapolitanFoodType.create(NeapolitanFoodType.java:43) ~[twilightdelight-1.3.1.jar%23810!/:1.3.1]
		at dev.xkmc.twilightdelight.init.registrate.TDItems.lambda$simpleFood$2(TDItems.java:51) ~[twilightdelight-1.3.1.jar%23810!/:1.3.1]
		at dev.xkmc.twilightdelight.init.registrate.TDItems.lambda$food$4(TDItems.java:68) ~[twilightdelight-1.3.1.jar%23810!/:1.3.1]
		at dev.xkmc.l2library.repack.registrate.builders.ItemBuilder.createEntry(ItemBuilder.java:242) ~[l2library-1.9.7.jar%23920!/:1.9.7]
		at dev.xkmc.l2library.repack.registrate.builders.ItemBuilder.createEntry(ItemBuilder.java:39) ~[l2library-1.9.7.jar%23920!/:1.9.7]
		at net.minecraftforge.common.util.Lazy$Fast.get(Lazy.java:55) ~[forge-1.19.2-43.2.21-universal.jar%23848!/:?]
		at dev.xkmc.l2library.repack.registrate.AbstractRegistrate$Registration.register(AbstractRegistrate.java:144) ~[l2library-1.9.7.jar%23920!/:1.9.7]
		at dev.xkmc.l2library.repack.registrate.AbstractRegistrate.onRegister(AbstractRegistrate.java:244) ~[l2library-1.9.7.jar%23920!/:1.9.7]
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2385!/:?]
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2385!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.21.jar%23845!/:?]
		... 31 more

Another possible culprit (Roots Classic):

	Caused by: java.lang.NullPointerException: Registry Object not present: rootsclassic:crystal_staff
		at java.util.Objects.requireNonNull(Objects.java:336) ~[?:?]
		at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.2.21-universal.jar%23848!/:?]
		at elucent.rootsclassic.ritual.RitualRegistry.lambda$static$0(RitualRegistry.java:37) ~[RootsClassic-1.19.2-1.1.35.jar%23760!/:1.19.2-1.1.35]
		at net.minecraftforge.registries.DeferredRegister.lambda$addEntries$1(DeferredRegister.java:388) ~[forge-1.19.2-43.2.21-universal.jar%23848!/:?]
		at net.minecraftforge.registries.RegisterEvent.register(RegisterEvent.java:59) ~[forge-1.19.2-43.2.21-universal.jar%23848!/:?]
		at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:388) ~[forge-1.19.2-43.2.21-universal.jar%23848!/:?]
		at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:330) ~[forge-1.19.2-43.2.21-universal.jar%23848!/:?]
		at net.minecraftforge.registries.__EventDispatcher_handleEvent_RegisterEvent.invoke(.dynamic) ~[forge-1.19.2-43.2.21-universal.jar%23848!/:?]
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.21.jar%23845!/:?]
		... 31 more

**Comment by bageldotjpg** [comment] 2023-10-08 17:05
Duplicate of #173

**Closed as completed by bageldotjpg** 2023-10-08 17:05 UTC
